### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#11]
Hello there,

I extract my redux logic to a different repo so I can used this shared code with my react application and react-native application.

The thing is that I'm not into use the standard navigator because it not respect the concept of "your state must be a snapshot of your UI over time".
When I say that is I can push a new screen to the navigator but doing that it doesnt change the state. 
I thought to create a separated reducer to control my navigation but doing that I'll not respect the one way data flow paradigm.

With that in mind I started to have some brainstorm with some people into the redux channel on discord and some one suggest me this module.

I'm pretty excited about the idea but I need to know how far are you guys on it, what is the roadmap, what is the next steps of implementation.

Since the idea of this project is exactly what I was thinking in build it will be a good idea if instead of creating from scratch I start to contribute to this one, however, to me be able to do that I need to know more about the project because unfortunately I dont have free time to spend in a project that will not be useful for me. ( I hope you understand that )

Maybe we can have a hangout chat or even here in github a discussion the project.

I hope you have a nice day and I'm kinda excited to be part of this !

**Comment by ericvicenti** [comment]
Keep in mind, even if the code doesn't imminently land in the main RN repo, it will still work and be easier to use than the current Navigator.

The roadmap is to get it adopted, and build some accompanying utilities to support it. As these companion tools evolve, the core will evolve as well.

I'm working on getting this adopted at FB. Some time in the next week or two, I plan to land this code in the main the react native repo. At which time I'll remove the code from this repo. It will come over in a few pieces- one big batch of new files and examples, a followup commit that changes the UIExplorer over to use it, and docs.

Your contributions would be greatly appreciated!

**Comment by lucasfeliciano** [comment]
That is good to hear.
Count on me on that.
I'm still working in some QA issues on my redux logic project, and after that I'll integrate with the react-native one so I'll start to use this navigator.

:)
