### ISSUE TITLE
Animations show shows current screen in place of previous/next?

### ISSUE THREAD

**Issue by satya164** [ericvicenti/navigation-rfc#12]
The gesture to go back seems to be showing the current screen in place of the previous screen. Same for the animation on navigations.

Here is a video - https://dl.dropboxusercontent.com/u/8501878/gesture.mp4

**Comment by rt2zz** [comment]
@satya164 its a bit hard to tell from that video, but I had a similar issue caused by me naively using the navState to render my view rather than the props provided to `renderScene`.

**Comment by satya164** [comment]
BTW it also happens in the examples included in the repo. I followed the examples to implement mine and seems like it uses `navState` too. Can you share your implementation?

**Comment by satya164** [comment]
Also, seems the props passed to `renderScene` are all animation related, and don't include route info.

**Comment by rt2zz** [comment]
here is the full class, although I think its a bit confusing and I can probably clean it up a lot: https://gist.github.com/rt2zz/8fd78922f914805428f9 

Basically the thing is navState looks something like

``` js
{routes: {...}, index: 0}
```

where index always represents the active index. however props that are passed to renderScene looks roughly like this:

``` js
{
      key: sceneRecord.key,
      sceneRecord,
      position: this._position,
      height,
      width,
      initWidth: this._lastWidth,
      initHeight: this._lastHeight,
    }
```

so to access your "route" the code would be:

``` js
renderScene={(props) => {
  let route = props.sceneRecord.get('route')
}}
```

Note: sceneRecord is an immutablejs map hence the `.get`

**Comment by satya164** [comment]
@rt2zz Thanks. Will try and let you know.

**Comment by satya164** [comment]
@rt2zz Thanks. This fixed my issue. We should document it somewhere.

**Comment by rt2zz** [comment]
@ericvicenti I think there are a number of areas like this where the api's can be improved with small changes. What is the current status of getting this into react-native core and do you want PR's against this project or should we wait until it lands in core?
