### ISSUE TITLE
Navigation for pure Flux app? 

### ISSUE THREAD

**Issue by hedgerwang** [ericvicenti/navigation-rfc#17]
I'd like to propose the minimum set of APIs that we'd need to build a flux style application with navigation.

Imagine that we're building a TodoList app with the ordinary flux implementation, and all my navigation states are maintained by one singleton flux store called **TodoNavigationStore**:

```

const appDispatcher = new Dispatcher();

class TodoNavigationStore extends FluxStore {
  constructor() {
    super(appDispatcher);
    this._tasks = new NavigationStack([new TaskRoute('first task')]);
  }

  getNavigationStack() {
    return this._tasks;
  }
}

module.exports = new TODONavigationStore();
```

and the navigation state is render by the **NavigationAnimatedView**

```
class TodoApp extends React.Component {
  static getStores() {
    return [TodoNavigationStore];
  }

  static calculateState() {
    return {
      navigationStack: AppNavigationStore.getNavigationStack(),
    }
  }

  render() {
    return (
      <NavigationAnimatedView
        navigationStack={this.state.navigationStack}
      />
    );
  }
}

TodoApp = Flux.createContainer(TodoApp);
```

as you could imagine, we'd be able to map the **add task** action to navigation changes.

```

class TodoNavigationStore extends FluxStore {

  // handle dispatcher action.
  __onDispatch(action): void {  
    switch (action.type) {
      case 'add_task':
        this._tasks = this._tasks.push(new TaskRoute(action.text));
        this.__emitChange();
    }
  }
}

```

of course, we could also map the **close task** action to navigation changes, too. 

```

class TodoNavigationStore extends FluxStore {

  __onDispatch(action): void {  
    switch (action.type) {
      // .....

      case 'close_task':
        const route = action.route;
        this._tasks = this._tasks.remove(route);
        this.__emitChange();
    }
  }
}

```

now let's consider a more complicated case. Say that we want to open a modal composer. When the composer is show, the tasks are hidden. So the store may look like this:

```
class TodoNavigationStore extends FluxStore {
  constructor() {
    // ...

    this._tasks = new NavigationStack([new TaskRoute('hello')]);

    this._showComposer = false;
    this._composer = new NavigationStack([new ComposerRoute]);
  }

  getNavigationStack() {
    return this._showComposer ? this._composer : this._tasks;
  }

```

and the actions that open or close the compose changes the navigation stack.

```
class TodoNavigationStore extends FluxStore {
  // ......

  getNavigationStack() {
    return this._showComposer ? this._composer : this._tasks;
  }

  __onDispatch(action): void {

    switch (action.type) {
      // ....
      case 'show_composer':
        this._showComposer = true;
        this.__emitChange();
        break;

      case 'hide_composer':
        this._showComposer = false
        this.__emitChange();
        break;

      case 'add_task':
        this._showComposer = false
        this._tasks = this._tasks.push(new TaskRoute(action.text));
        this.__emitChange();
        break;
    }
}

```

These code snippets should demonstrate that how could we build reactive flux application with navigation APIs that play nice with flux.

Having said that, here are the minimum set of APIs that I consider useful in flux application.
- **NavigationStack** : Immutable data type that represents the list of routes 
- **NavigationAnimatedView**:: The controlled component that renders the navigation stack and handles gesture and transitions.

Note that I don't mention anything about the **NavigationAction** or things like navigation reducer.

The idea is that when the application becomes complicated, it'd make sense to separate the navigation states from the views and manage the navigation state at once place.

I came to realize that there is no only one way to define the complete navigation actions and hierarchies of apps so we should not focus on making something that fits all.

Instead, we should provide basic utils to people to build navigation with their own existing architecture such as flux. 

Feedback is welcomed.

**Comment by ericvicenti** [comment]
I agree, we should focus on providing the utilities for people to write high-quality navigation code, but not force anything upon them.

This was one of my major focuses with this RFC- that the tools would be decoupled, but work well together. As you said, you don't need to use the reducer/actions, or the containers.

But developers also don't need to use the NavigationAnimatedView if it constrains them too much. Instead they could do something wacky like a [wraparound pager](https://github.com/facebook/react-native/issues/5100), or bridge to native components like ScrollView, ViewPager, or NavigatorIOS.

**Comment by ericvicenti** [comment]
Closing this for now. feel free to re-open if you have more actionable feedback!
