### ISSUE TITLE
Rendering different components

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#18]
There is a way to push a new scene to the navigation with the scene name and a component to be rendered in that scene?

edit: I'm writing a better example case. I'll udpate this issue in a bit

**Comment by ericvicenti** [comment]
Currently the API doesn't make any assumptions about the route. So you could push a route like this:

```
this.onNavigation(NavigationActions.Push({ name: 'My Title', component: MyComponent }));
```

**Comment by ericvicenti** [comment]
But it might not be the best idea, because now you need to load MyComponent into memory before you ever link to it. At Fb, we currently use route mappers. Something like this:

```
getComponentForPageRoute(route) {
  switch(route.name) {
    case 'FBGroupRoute':
      return require('FBGroupView');
    default:
      return require('FBNotFoundView');
}
```

**Comment by lucasfeliciano** [comment]
Sorry for the delay, I was writing a big spec with a lot of details but I closed my browser before submitting the update so it got lost.

I'll make it short:

I'm doing this to render different components in my application, this is a example:

``` javascript
var App = React.createClass({
  render: function() {
    return (
      <NavigationContainer.RootContainer
      initialState={new NavigationState(['first page'], 0)}
      reducer={NavigationReducer}
      renderNavigator={(navState, onNavigation) => (
        if(route === 'multiProduct') {
          return <MultiProdcut />
        }
        if(route === 'selectedProduct') {
          return <selectedProduct />
        }  
        if(route === 'feedback'){
          return <feedback />
        }
      )}
      />
    );
  }
});
```

But I'm in a situation where I need at least be able to pass some props to the navigation:
It would be nice to do something like this:

``` javascript
onNavigation(new NavigationReducer.Actions.Push('newRoute', {someId: 'someData'}));
```

or

``` javascript
onNavigation(new NavigationReducer.Actions.Push(
  {name: 'newRoute', 
   props: {someId: 'someData'}
}));
```

Then in the navigatior:

``` javascript
var App = React.createClass({
  render: function() {
    return (
      <NavigationContainer.RootContainer
      initialState={new NavigationState(['first page'], 0)}
      reducer={NavigationReducer}
      renderNavigator={(navState, onNavigation, navProps) => (
        if(navState === 'multiProduct') {
          return <MultiProdcut />
        }
        if(vavState === 'selectedProduct') {
          return <selectedProduct props={navProps} />
        }  
        if(navState === 'feedback'){
          return <feedback />
        }
      )}
      />
    );
  }
});
```

This is just a simple example but it is a nice feature to have, otherwise I would need to have two different dataflows ( one from the navigator and one from my redux store)  just to control what to render.

**Comment by satya164** [comment]
Isn't this already possible with current implementation?

``` js
onNavigation(new NavigationActions.Push({
    name: "product",
    props: {
        id: 101
    }
}));
```

Then, in your `renderScene`,

``` js
props => {
    const route = props.sceneRecord.get("route");

    switch (route.name) {
    case 'product':
        return <Product {...route.props} />;
    }
}
```

**Comment by lucasfeliciano** [comment]
@satya164 Thank you for the reply.

This is perfect and really fits my requirements, I tried to find something in the examples but I'm having such a busy week that I couldn't look into the code properly.

So that is implemented, right?

**Comment by satya164** [comment]
Yes. I use something similar in my app. If you need an example, here is my code - https://github.com/satya164/Croma/tree/navnext/app/navigation

**Comment by lucasfeliciano** [comment]
@satya164 Thank you again and have a nice day :)

Case closed :)
