### ISSUE TITLE
RFC: Using JSON objects for navigation state and routes

### ISSUE THREAD

**Issue by ericvicenti** [ericvicenti/navigation-rfc#19]
**Problem 1:** We want to easily be able to save NavigationState to disk, but the (de)serialization is hard

**Problem 2:** The relationship between route and sub-navigationState is ambiguous. Currently the NavigationReducer demands that the route implement getNavigationStack and setNavigationStack in order to support the OnRouteNavigationState action. This feels complicated and awkward

**Proposed solution:** We should encourage people to model the navigation state state in dumb JSON-serializable objects rather than class instances. A NavigationState can be a string or an object, so it can be a URL or a deep object. Each child route is another NavigationState, so the deeply-nested navigation structure is simple and easy to serialize.

``` javascript
const NavigationStateUtils = require('NavigationStateUtils'); // this doesn't exist yet
type NavigationState = string | {
  key: ?string,
  index: ?number,
  routes: ?Array<NavigationState>,
};
var navState: NavigationState = { routes: [ 'First Page' ], index: 0, }

// in your reducer:
return NavigationStateUtils.push(navState, 'Second Page');
// output:
{ routes: [ 'First Page', 'Second Page' ], index: 1 }
```

This becomes handy when we want to do sophisticated actions, like the composition example with independent navStacks inside tabs:

``` javascript
var navState: NavigationState = {
  routes: [
    {key: 'tab0', routes: ['First Page in Tab 0' ], index: 0 },
    {key: 'tab1', routes: ['First Page in Tab 1'], index: 0 },
  ],
  index: 1
};

// in your reducer:
var tabToPushOn = 'tab0';
return NavigationStateUtils.setRoute(
  tabToPushOn,
  NavigationStateUtils.push(
    NavigationStateUtils.getRoute(tabToPushOn),
    'Second Page on Tab 0'
  )
)
// output:
{
  routes: [
    {key: 'tab0', routes: ['First Page in Tab 0', 'Second Page on Tab 0' ], index: 1 },
    {key: 'tab1', routes: ['First Page in Tab 1'], index: 0 },
  ],
  index: 1
};
```

cc @sahrens @hedgerwang. Thanks @gaearon for chatting last week and planting this idea in my head

**Comment by satya164** [comment]
In my project, the approach I've taken is that I've a set of route descriptions which are plain, JSON serializable objects, and a route mapper which maps those routes to components. The renderScene function can then use the map to figure out what to render. Having routes as JSON is nicer, more readable, and helps with persistence.

**Comment by brentvatne** [comment]
This is great @ericvicenti -- I think this approach is much cleaner. cc @ide

**Comment by ericvicenti** [comment]
Ok, I just dropped this in. Please file additional feedback as separate issues!
