### ISSUE TITLE
NavigationStack

### ISSUE THREAD

**Issue by devknoll** [ericvicenti/navigation-rfc#2]
**#bikeshedding**

> A `NavigationStack` is a list of arbitrary routes and an _index_

The index is a little confusing -- a stack implies LIFO, and navigation usually (at least on iOS, browsers) is push/pop/popTo. The current route is just what's on top.

Is there a use case we're trying to support with the index and the class? If so, it might be nice to rename this to `RouteList` or something.

**Comment by ericvicenti** [comment]
Take browser history for example- it is often referred to as a "stack", but you can go forward as well as backward.

But I agree that the "stack" name is an abuse. I don't mind "list", but we still need to convey that an index along the list is part of the data structure.

@hedgerwang called this NavigationRouteStack, but I was hoping for a shorter name. Maybe `NavigationList`?

**Comment by devknoll** [comment]
Is there a precedent for forward navigation in apps? :smile: That seems strange. But could also just be another stack of popped routes :wink: 

But a different name would be ok. `NavigationList` seems strange to me, since it's (according to the docs) a list of _routes_.

Apologies for bikeshedding.

**Comment by ericvicenti** [comment]
A few cases of 'forward' navigation in native apps:
- Tapping 'forward' on a series of NUX pages
- Scrolling down a long scroll view where your position is tracked
- Some apps (like alien blue) allow you to go back and then forward similar to a browser
- Tabs (start on tab one, go to tab 2)

Interesting idea to add another stack for popped routes. It sounds doable, but then it is possible that a route will have several sub-NavigationStacks, and that would increase complexity.

Regarding naming, I was hoping we could use a `Navigation` prefix, to make it clear that the navigation stack is meant to be used by other `Navigation*` things like NavigationAnimatedStackView. I'm open for re-consideration, but that was my thinking. Do we have any ideas for a name other than `NavigationStack` or `NavigationList`? It sounds like `NavigationRouteStack` is probably the way to go

**Comment by hedgerwang** [comment]
I'd just call it as (immutable) NavigationState. One thing to notice is that a route is unique within the navigation state, so it's more like a OrderedSet. On the other hand, it also provides the information of the currently active route as 'index'. 

Having said that, let's not try to treat like a List, Map or a Set because they are just implementation details.

**Comment by ericvicenti** [comment]
Good point about uniqueness of routes!

`NavigationState` sounds fine to me. If nobody objects or has a better name, I'll rename to that in a few days.

**Comment by jadsonlourenco** [comment]
**NavigationState** is better (opinion).

**Comment by devknoll** [comment]
:+1: to NavigationState.

Again... apologies for the bikeshedding.

**Comment by ericvicenti** [comment]
Renamed!

Also, `NavigationStackView` is now `NavigationView`. `NavigationAnimatedStackView` is now `NavigationAnimatedView`

**Comment by jadsonlourenco** [comment]
Great job! Also the new API is better, TY!
