### ISSUE TITLE
Dependency of redux

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#22]
Why the navigator depends on redux?

I dont think it is a good idea of having the navigation store as the same as our application.

It should be transparent for us. The navigator should be aware of his own state, why should I pass my store, doesn't make sense for me, maybe I'm missing something

In my case I don't even have redux installed on my react-native view project, it is in another project that the view can import as a module and then with react-redux connect the store to my components.

**Comment by ericvicenti** [comment]
This code does not depend on redux, it is inspired by it. If you don't want to follow flux or redux patterns, you don't have to. I have found that it is easier to structure the application by putting all the application state into one object and reducing it.

When you say `The navigator should be aware of his own state`, that is exactly what `NavigationContainer.RootContainer` does! It manages the state for you.

Please file another issue if you have a more specific question or problem :-D
