### ISSUE TITLE
Undefined is not a constructor when calling NavigationActions.push

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#24]
I have this  component which is already been renderized by the navigator and router.

``` javascript
var First = React.createClass({
  render: function() {
    return (
      <View><Text onPress={ () => {
        this.props.onNavigation(
          new NavigationActions.push({name: 'second', props: {id: 'someId'}})
        );
      }}>GOOOO</Text></View>
    );
  }
});
```

But when I click on the button to trigger the push of the new route. I get this error below:

![screen shot 2016-01-20 at 16 33 55](https://cloud.githubusercontent.com/assets/968014/12453506/db5e9a6e-bf93-11e5-9458-d1b3d1e34ea7.png)

**Comment by ericvicenti** [comment]
Sorry about this. I changed the API last night but I didn't update the docs. You can fix the issue by removing the `new` statement from your code. I'll update the docs this week!

**Comment by lucasfeliciano** [comment]
Thanks, and I see that you are not using classes anymore.
:+1:
