### ISSUE TITLE
Position and Layout props

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#26]
Since you guys changed the API I was trying to make the navigator work again.

Every time that I make it work something is changed in your code and I have to understand what is going on and make the changes. I'm in a infinite loop here hahah.

Now I'm struggling to know from where the `position` and `layout` props comes from.

_edit: Just debugged this project and realised that `position` it is a `AnimatedValue`, but still have no idea were comes from._

I'm using the architeture that @satya164  suggested.
However I'm getting this error: `Can't find variable: position`

I'll share with you what I have here
- App.js

``` javascript
var App = React.createClass({
  render: function() {
    return (
      <NavigationContainer.RootContainer
        initialState={{routes: [ 'first' ], index: 0}}
        renderNavigator={renderNavigator}
      />
    );
  }
});
```
- renderNavigator.js

``` javascript
const renderNavigator = (navState, onNavigation) => {
  if (!navState) {
    return null;
  }

  return (
    <NavigationAnimatedView
      navigationState={navState}
      style={styles.animatedView}
      renderOverlay={renderOverlay(navState, position, layout, onNavigation)}
      renderScene={renderScene(route, index, navState, position, layout, onNavigation)}
      />
  );
};
```
- renderOverlay.js

``` javascript
const renderOverlay = function(navState, position, layout, onNavigation) {
  return props => {
    return (
      <NavigationHeader
        {...props}
        renderLeftComponent={(route, index) => {
          if (index === 0) {
            return null;
          }

          return <NavigationExampleBackButton onNavigation={onNavigation} />;
        }}
        renderTitleComponent={route => <NavigationHeaderTitle>{route}</NavigationHeaderTitle>}
        />
    );
  };
};
```
- renderScene.js

``` javascript
const renderScene = function(route, index, navState, position, layout, onNavigation) {
  return props => {
    const route = props; // eslint-disable-line react/prop-types

    const {
      component: RouteComponent
    } = routeMapper(route);

    return (
      <NavigationCard
        {...props}
        route={route}
        index={index}
        navState={navState}
        position={position}
        layout={layout}
        >
        <RouteComponent
          {...route.props}
          style={styles.container}
          onNavigation={onNavigation}
          />
      </NavigationCard>
    );
  };
};
```
- routerMap.js

``` javascript
export default function(route) {
  switch (route) {
    case 'first':
      return {
        component: First,
        title: 'First Route'
      };
    case 'second':
      return {
        component: Second,
        title: 'Scond'
      };
    default:
      return null;
  }
}
```

**Comment by satya164** [comment]
It'll be something like like this (instead of the `props` property, `renderScene` and `renderOverlay` receive `route`, `index`, `navState`, `position` and `layout`),

``` js
const renderOverlay = function(onNavigation) {
  return (route, index, navState, position, layout) => {
    return (
      <NavigationHeader
        key={route}
        route={route}
        index={index}
        navState={navState}
        position={position}
        layout={layout}
        renderLeftComponent={(route, index) => {
          if (index === 0) {
            return null;
          }

          return <NavigationExampleBackButton onNavigation={onNavigation} />;
        }}
        renderTitleComponent={route => <NavigationHeaderTitle>{route}</NavigationHeaderTitle>}
        />
    );
  };
};
```

**Comment by lucasfeliciano** [comment]
@satya164 Still have the same problem.

It is complaning in the `renderNavigator.js`:

``` javascript
const renderNavigator = (navState, onNavigation) => {
  if (!navState) {
    return null;
  }

  return (
    <NavigationAnimatedView
      navigationState={navState}
      style={styles.animatedView}
      renderOverlay={renderOverlay(navState, position, layout, onNavigation)}
      renderScene={renderScene(route, index, navState, position, layout, onNavigation)}
      />
  );
};
```

I tried to wrap the return into a function passing the same things like you did in your comment above but I get:

![screen shot 2016-01-21 at 15 58 13](https://cloud.githubusercontent.com/assets/968014/12483910/d55d074e-c057-11e5-8672-03de07f258e5.png)

If I don't change the navigator I get the same error saying that can't find the variable position on this line of the renderNavigator.js:

`renderOverlay={renderOverlay(navState, position, layout, onNavigation)}`

**Comment by satya164** [comment]
It should be `renderOverlay={renderOverlay(onNavigation)}`

**Comment by satya164** [comment]
I should rectify the naming a bit. the `renderOverlay` function is not actually the function which renders the overlay. I should call it `getOverlayRenderer` and `getSceneRenderer` respectively. These functions return the actual function which renders the overlay and scene. They are just used to provide the `onNavigation` variable to the returned functions.

**Comment by satya164** [comment]
So,

```js
const getOverlayRenderer = (navState, onNavigation) => {
  return (route, index, navState, position, layout) => {
    return (
      <NavigationHeader
        key={route}
        route={route}
        index={index}
        navState={navState}
        position={position}
        layout={layout}
        renderLeftComponent={(route, index) => {
          if (index === 0) {
            return null;
          }

          return <NavigationExampleBackButton onNavigation={onNavigation} />;
        }}
        renderTitleComponent={route => <NavigationHeaderTitle>{route}</NavigationHeaderTitle>}
        />
    );
  };
};
```

And then,

```js
renderOverlay={getOverlayRenderer(navState, onNavigation)}
```

Same for `renderScene`.

**Comment by satya164** [comment]
So,

``` js
const getOverlayRenderer = onNavigation => {
  return (route, index, navState, position, layout) => {
    return (
      <NavigationHeader
        key={route}
        route={route}
        index={index}
        navState={navState}
        position={position}
        layout={layout}
        renderLeftComponent={() => {
          if (index === 0) {
            return null;
          }

          return <NavigationExampleBackButton onNavigation={onNavigation} />;
        }}
        renderTitleComponent={route => <NavigationHeaderTitle>{route}</NavigationHeaderTitle>}
      />
    );
  };
};
```

And then,

``` js
renderOverlay={getOverlayRenderer(onNavigation)}
```

Same for `renderScene`.

**Comment by satya164** [comment]
Note that I've not tested anything I've written here. So it might not be correct. I'll update my code soon.

**Comment by lucasfeliciano** [comment]
Sure, I made some progress here knowing that changes.

But somehow the position is not getting to `NavigationHeader`

When the header tries to call:
`opacity: this.props.position.interpolate`

there is no position on my props, so it tried to call the `interpolate` on a undefined object

**Comment by satya164** [comment]
Can you share your code again?

**Comment by lucasfeliciano** [comment]
Sure, here we go:
- app.js

``` javascript
var App = React.createClass({
  render: function() {
    return (
      <NavigationContainer.RootContainer
        initialState={{routes: [ 'first' ], index: 0}}
        renderNavigator={renderNavigator}
      />
    );
  }
});
```
- renderNavigator.js

``` javascript
const renderNavigator = (navState, onNavigation) => {
  if (!navState) {
    return null;
  }

  return (
    <NavigationAnimatedView
      navigationState={navState}
      style={styles.animatedView}
      renderOverlay={getOverlayRenderer(navState, onNavigation)}
      renderScene={getSceneRenderer(navState, onNavigation)}
      />
  );
};
```
- getOverlayRenderer

``` javascript
const getOverlayRenderer = function(navState, onNavigation) {
  return (route, index, navState, position, layout) => {
    return (
      <NavigationHeader
        key={route}
        route={route}
        index={index}
        navState={navState}
        position={position}
        layout={layout}
        renderLeftComponent={(route, index) => {
          if (index === 0) {
            return null;
          }

          return <NavigationExampleBackButton onNavigation={onNavigation} />;
        }}
        renderTitleComponent={route => <NavigationHeaderTitle>{route}</NavigationHeaderTitle>}
        />
    );
  };
};
```
- getSceneRenderer

``` javascript
const getSceneRenderer = function(navState, onNavigation) {
  return (route, index, navState, position, layout) => {
    const {
      component: RouteComponent
    } = routeMapper(route);

    return (
      <NavigationCard
        route={route}
        index={index}
        navState={navState}
        position={position}
        layout={layout}
        >
        <RouteComponent
          {...route.props}
          style={styles.container}
          onNavigation={onNavigation}
          />
      </NavigationCard>
    );
  };
};
```

**Comment by satya164** [comment]
Wait! My mistake. `renderScene` and `renderOverlay` take different arguments. Need to change the `getOverlayRenderer` to this,

``` js
const getOverlayRenderer = onNavigation => {
  return (navState, position, layout) => {
    return (
      <NavigationHeader
        position={position}
        layout={layout}
        renderLeftComponent={(route, index) => {
          if (index === 0) {
            return null;
          }

          return <NavigationExampleBackButton onNavigation={onNavigation} />;
        }}
        renderTitleComponent={route => <NavigationHeaderTitle>{route}</NavigationHeaderTitle>}
        />
    );
  };
};
```

And then,

``` js
renderOverlay={getOverlayRenderer(onNavigation)}
```

**Comment by lucasfeliciano** [comment]
@satya164 REALLY thanks for your help.
I Made a huge progress here, now I can render my scenes and the header.

However after I change the `push` method to upper case and I tried to push a new route like this:

``` javascript
var First = React.createClass({
  render: function() {
    return (
      <View>
        <Text 
          style={{padding: 100}} 
          onPress={ () => {
            this.props.onNavigation(
              NavigationActions.Push({name: 'second', props: {id: 'someId'}})
            );
          }}>
          GOOOO
        </Text>          
      </View>
    );
  }
});
```

I get this error:

![screen shot 2016-01-21 at 16 49 35](https://cloud.githubusercontent.com/assets/968014/12485443/1deb0a5e-c05f-11e5-8bf7-6cfeb61579b9.png)

**Comment by satya164** [comment]
Is it possible that you've an old copy of the `NavigationActions` file? This shouldn't happen.

**Comment by lucasfeliciano** [comment]
You are the man!  :+1: 

it is working now.

Last question:

How do I pass props now? Because I can see in the code that you need to push a string, which is the route name
:)

**Comment by ericvicenti** [comment]
Glad you got it working! Thanks @satya164 for the guidance!

But it looks like things are more complicated than we need with the `getScene/OverlayRenderer`. It seems to be needed in this case to pass `onNavigation` down to `RouteComponent`. To avoid the getRenderer pattern, you could instead wrap RouteComponent with a container:

`FirstSceneView = NavigationContainer.create(FirstSceneView);`

Now this view will always get the `onNavigation` and `navigationState` props from its closest parent container- in this case it would be the root container.

For passing extra props, check out the composition example to see routes that are not strings. Or, you can have your route mapper return additional props.

**Comment by satya164** [comment]
@ericvicenti Didn't realize that. Thanks for the tip :D

**Comment by lucasfeliciano** [comment]
Should I close the issue?

**Comment by ericvicenti** [comment]
Suit yourself :smile: Closing out this issue for now

**Comment by lucasfeliciano** [comment]
Good point @ericvicenti.

About the props I checked out the composition example and this is too much complexity for just passing props, it is completely an overkill

Before I was able to pass props like @satya164 said in https://github.com/ericvicenti/navigation-rfc/issues/18#issuecomment-172576513  it was simple and functional.
