### ISSUE TITLE
Memory increasing and delays in transitioning on current Navigator, is it the same in this proposal?

### ISSUE THREAD

**Issue by afilp** [ericvicenti/navigation-rfc#28]
Does this new implementation suffer from the memory problems of the current Navigator?

See this issue:
https://github.com/facebook/react-native/issues/4740

Will we have the same problems?

This is the problem i have with the current Navigator, will I have the same problem with this implementation too? 

In our iOS app, **memory is increasing** even when the app is "idle" (user does nothing and views are settled). 

If I use the `replace` instead of `push` in the Navigator then this does not happen, so it is clearly a `Navigator` issue. Is there any fix for this, as this made us use only the `replace` method which means that we have no `back` functionality?

**Comment by ericvicenti** [comment]
I commented on your original issue. Neither navigation solution should have this problem!

If you have a simple code sample that demonstrates the issue, it will help the core team look into the leak.

I'm going to close this issue out for now. Please open more issues if you have any feedback, or if you notice memory leaks with the new nav code!
