### ISSUE TITLE
JSON value '<null>' when chrome debug is enable

### ISSUE THREAD

**Issue by lucasfeliciano** [ericvicenti/navigation-rfc#30]
If I have `chrome debug` enable I get this error

<img width="432" alt="screen shot 2016-01-26 at 11 30 54" src="https://cloud.githubusercontent.com/assets/968014/12578354/a6bd28b6-c420-11e5-9646-cfbcdaab6416.png">

**Comment by ericvicenti** [comment]
Should be fixed now by avoiding the transform. I've let the RN team know about this issue
