### ISSUE TITLE
"key" property for routes

### ISSUE THREAD

**Issue by satya164** [ericvicenti/navigation-rfc#33]
Seems every route needs to provide a Key property which we use as React keys. Any idea on how to handle this when there are multiple instance of the same route in the state? Keys no longer stay unique!

**Comment by rt2zz** [comment]
@satya164 in my case I define the key with a unique id taken from route props. e.g. `key={route.key + route.props.resourceId }`. 

Another option would be to use the routeStack index which is always unique. Perhaps this should be the default key?

**Comment by lucasfeliciano** [comment]
I think that should be transparent for us.

i've been setting the key as the same string as the route name.

So would be a nice idea to have to follow this as a default value.

But, if there is a route more then one time in the array we should count how many times tthat string apears in the array and concatenate with the name. so lets say we have this array of routes:

`['myRoute', 'anotherRoute']`

if we push `myRoute` again to the array we could count how many `myRoute` appears in the array then concat that value, so we will have this.

`['myRoute', 'anotherRoute', 'myRoute1']` <- that is the respectives `KEYS` to the routes:
 `['myRoute', 'anotherRoute', 'myRoute']`

**Comment by rt2zz** [comment]
I do not think there is any clean way to inject a key prop into the results of `renderScene`. We could wrap the result in a view with the key but this seems bad. So presumably then setting keys of `['myRoute', 'anotherRoute', 'myRoute1']` would be up to the implementer.

In this case I think we should just add a sanity check that warns if there is no key set, and furthermore document key assignment options, with the easiest being to simply set `key={index}`.

**Comment by ericvicenti** [comment]
Agreed we should have a sane `index` fallback for the key.

Originally this RFC did not have a key for each route, but it became difficult to distinguish between when we wanted to 'replace' a route and mount a new view for it, compared to updating the existing one. This is already solved in React through the key prop, so I thought exposing it was the only sane way forward.

In general, your action will be requesting a specific kind(name) of route, but if you want to present a new route for it, your reducer should set the route key to disambiguate between other instances of that route. For views like tabs, you generally want to jump to the existing route and you won't need a custom key. But for a navigation stack, you will always want a new key when you push something.

I'm thinking about ways to make a reducer that automatically works for all nav stacks, and a re-usable reducer that can be used for any set of tabs.

Still I'm open to suggestions if somebody has an alternative to putting keys in routes.
