### ISSUE TITLE
Animated transitions using redux

### ISSUE THREAD

**Issue by Kureev** [ericvicenti/navigation-rfc#37]
This issue is a follow-up for https://github.com/ericvicenti/navigation-rfc/issues/29.

As It was mentioned in the #29, there is a pretty simple way to make this reference implementation working with a redux (see an issue above for details). But the one question left: animated transitions using redux.

I believe we all want to keep our components as stateless as possible, but for me it looks crazy to pipe a transition animation values thru the redux flow. I'm wondering if during this discussion we can find a nice solution for this.

Variants I can see so far:
- Use a native code for the transition management. Simply put, it's about writing a native implementation for the animation queue. Every time we need to render a navigation route, we send a route component and a bunch of animation instructions to the native platform. A native platform builds an `RCTView` based on the passed component and perform a transition using an animation instructions we supplied.
  I think this variant can help us solving a performance issue we have with `Navigator`. But of course, on the other hand it means having a two native implementation for iOS and Android. If we go this way, we need to have a strong iOS and Android developers.
- Use `Animated` library. That will be a bit crazy: just imagine sending thousands of actions for every transition :smiley:. Plus it doesn't solve a performance issue - if JS thread will be busy, it'll drop a FPS. But, this is the simplest possible implementation I can imagine.

If you have any ideas about this, please, let me know.

**Comment by ericvicenti** [comment]
We use Animated right now for this, as you can see from NavigationAnimatedView, NavigationCard, and NavigationHeader.

The problem, as you say, is performance of running the animations on the JS thread. For now, that is a known problem. Animated is designed in such a way to support driving the animations from the main thread. Until that gets fixed on both platforms, we are still likely to drop frames. @kmagiera is already hacking on this for fire-and-forget animations on Android: https://github.com/facebook/react-native/pull/5613

We still need to move to Animated.Event to make sure our gestures can happen on the main thread as well: https://github.com/ericvicenti/navigation-rfc/issues/38
