### ISSUE TITLE
Correlation between state.key and actual component

### ISSUE THREAD

**Issue by Kureev** [ericvicenti/navigation-rfc#39]
Hi @ericvicenti,

I have a question regarding a navigation state you store. As I see from the source, you propose to store only `key`. Would it be correct to assume that mapping between key <---> component supposed to happen inside a `renderScene`?

**Comment by lucasfeliciano** [comment]
:+1:

**Comment by ericvicenti** [comment]
You can store more than just key (thats just what the simpler example code does). What we typically store at Fb is a name/type of the state, some params, and a key to keep it unique.

And yep, you would do the mapping in `renderScene`
