### ISSUE TITLE
Problem with basic example code

### ISSUE THREAD

**Issue by ttraenkler** [ericvicenti/navigation-rfc#40]
Dear Eric,

Thanks for your work on the NavigationExperimental - we just pulled the 0.21 react-native release and were glad to see you provided an implementation that works well with Redux.

We tried the NavigationBasicExample as a starter - however if we replicate the example  we get an undefined is not an object (evaluating initialStates.length) regarding the NavigationStackReducer.js:88 - could you help us fix this error in the example code or hint at if it’s on our end what we have done wrong?

Kind regards,
Thomas

**Comment by ericvicenti** [comment]
Please test the latest master code, as NavigationExperimental is still changing pretty quickly.
