### ISSUE TITLE
Use navigation reducers within unit tests

### ISSUE THREAD

**Issue by aksonov** [ericvicenti/navigation-rfc#44]
I'm doing mock of 'react-native' within unit tests (otherwise it doesn't compile) and is there any way to extract reducers from there?

**Comment by aksonov** [comment]
Ok, i've copied all reducers manually and changed require(..) calls, but maybe there is better way...

**Comment by ericvicenti** [comment]
I'm not sure exactly what your goal/problem is. Can you link to your current code? I may be able to help

**Comment by aksonov** [comment]
I'm working on new release of react-native-router-flux component that will allow to create needed reducer for whole hierarchy of routes for lazy users :) Initially i wanted to combine your StackReducer & TabsReducer but decided to create own one (maybe it was wrong decision)... So maybe you could close it, but possibility of usage predefined reducers with own ones and test them would be really great...

**Comment by ericvicenti** [comment]
It is great that you created your own reducers. Thanks for working on a more declarative setup!

I'll close it for now. Feel free to open up more specific issues

**Comment by aksonov** [comment]
@ericvicenti, @hedgerwang I've just released new version of react-native-router-flux based on your API. Thanks for great improvement of react native navigation API. Any feedback would be very appreciated.
