### ISSUE TITLE
JumpAction handling for nested TabReducers?

### ISSUE THREAD

**Issue by aksonov** [ericvicenti/navigation-rfc#45]
If TabsReducer contains another TabsReducer, how i can change inner tab index? JumpActions changes root one...

**Comment by ericvicenti** [comment]
First of all, I would recommend pointing to react-native master, where the API has changed a bit.

To do that, you can update your package.json and run npm install: https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/commit/e1fd1a7ec9f3320bafffb28abf4a240c78bc9774#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R9

You probably have a reducer that handles the set of tabs you want to switch. You can extend that reducer to handle a custom action that changes the current index of that navigationState.
