### ISSUE TITLE
Is there any working example?

### ISSUE THREAD

**Issue by pie6k** [ericvicenti/navigation-rfc#46]
I have some pain reading docs - it's hard for me to get all the concepts, reducers idea etc. It's always much easier to understand what does what when you see live example when you see how each part is needed and is working together with other parts.

Is there any example showing as much aspects of this Navigator as possible?

**Comment by ericvicenti** [comment]
Yes, the example code has been the main form of documentation so far: 

https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/NavigationExperimental

The most comprehensive example is either the "composition" example, or the UIExplorer itself:

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorerApp.ios.js
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorerApp.android.js

**Comment by IanVS** [comment]
FYI it looks like these examples have moved to https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/js/NavigationExperimental
