### ISSUE TITLE
Integration with redux guide?

### ISSUE THREAD

**Issue by aksonov** [ericvicenti/navigation-rfc#52]
It is not clear (from docs) how to share state between redux & navigation. I could combine all existing redux reducers with navigation reducers but how to use common state?

**Comment by aksonov** [comment]
For now i see that props.navigateTo is 'alternative' of Redux props.dispatch() Could they be used together or i have to migrate from Redux to Navigation API?

**Comment by ericvicenti** [comment]
You shouldn't share state between NavigationRootContainer and redux, they should be held together.

If you use redux, use props.dispatch. If you store your state in NavigationRootContainer, use onNavigate.

**Comment by alexprice1** [comment]
@ericvicenti Would you suggest just using `NavigationAnimatedView` or `NavigationCardStack` without `NavigationRootContainer`? If so, would we have to reimplement the benefits of `NavigationRootContainer`?

Benefits:
1. Can save state to disk to persist navigation state over refreshes or app updates
2. Listens to Linking for url opening, and BackAndroid for easy back button support

**Comment by alexprice1** [comment]
Sorry, ignore my comment. Finally found a pretty good guide.

Here it is if anyone else is looking:

https://github.com/jlyman/RN-NavigationExperimental-Redux-Example
