### ISSUE TITLE
How does navigation work with TabBarIOS?

### ISSUE THREAD

**Issue by 5amfung** [ericvicenti/navigation-rfc#57]
I'm still trying to wrap my head around this.  All the examples I have found doesn't use TabBarIOS and tried to reinvent the wheel.

**Comment by ericvicenti** [comment]
TabBarIOS handles the switching of screens itself, and does not take it in as a prop. IE, it is an uncontrolled component, and NavigationExperimental needs to work with controlled components. Thats why the examples don't use it, and we have the same problem with NavigatorIOS.

It would be fantastic if somebody in the community volunteered to upgrade these components to be declarative and follow React best practices.
