### ISSUE TITLE
Scene Registry

### ISSUE THREAD

**Issue by mschipperheyn** [ericvicenti/navigation-rfc#64]
Ive been looking in the documentation for some kind of Route/Scene Registry component.
It would be a component that holds all the known Screens (Home, Registration, etc), a function to retrieve the Screen component lazily, a way to parse a route path (as opposed to a key): (account/profile, account/shoppingcart, account/user/{id}). I havent found it yet in the documentation. Is that something that is part of the concept?

**Comment by ericvicenti** [comment]
Right now this is left up to the app developer. It would be great to see the community contribute additional modules to handle the remaining pieces:
- Utility to map from URIs to actions
- Factory that creates a reducer to go from actions to nav state, and a mapping function that can go from a child state to a scene view
- Higher level view that utilizes the state-view map to render all of the scenes

**Comment by mschipperheyn** [comment]
Im in the process of whipping something up. Ill release it when its ready.

**Comment by jmurzy** [comment]
@mschipperheyn I've been working on a project, [react-router-native](https://github.com/jmurzy/react-router-native), that might pique your interest. Any feedback would be greatly appreciated.

**Comment by mschipperheyn** [comment]
@jmurzy Looks cool and in line with what I've been doing myself.
