### ISSUE TITLE
onBack instead of onNavigate?

### ISSUE THREAD

**Issue by ptomasroos** [ericvicenti/navigation-rfc#80]
Today its quite hard to know which underlying types are propagated through the onNavigate function.
It would be better if we could send a func down stream what should happen when a back happens or whatever else navigation might occur.

**Comment by hedgerwang** [comment]
@ptomasroos:
Yes.
We'll remove `onNavigate` and replace it with `onNavigateBack` soon.

**Comment by ptomasroos** [comment]
Awesome @hedgerwang! High five!

**Comment by ptomasroos** [comment]
Fixed by https://github.com/facebook/react-native/commit/fb0007d85323909ab652bf97166744fa7e17daab
