### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by aksonov** [ericvicenti/navigation-rfc#81]
I'm author of react-native-router-flux and have quite big community here and now we have many problems with breaking changes with almost each new React Native version. We did a lot of efforts to migrate from RN0.22 to RN0.26. And now there is no sense to adopt RNRF to 0.2  because 0.28-rc introduces other breaking changes.

I thought when navigation-rfc became part of RN, its API will be more stable, but i was wrong. Is there any way to clone NavigationExperimental as separate component (navigation-rfc?) until API will be not stable? This way we could stick to specific version of navigation-rfc, and users will not have problems after each RN upgrade.

Is there any roadmap of NavigationExperimenal? When it will be stable?

**Comment by jmurzy** [comment]
You should watch @ericvicenti's ReactEurope [talk](https://www.youtube.com/watch?v=dOSwHABLvdM&list=PLRbTavRQe30JD6mrAaZO5FGysOlwQETUr&index=7). It'll answer most of your questions. In short, there will be no more breaking changes that are as big as what you've experienced in the last few releases. I would say you should still expect [some changes](https://github.com/facebook/react-native/issues/6184#issuecomment-195107862) [here](https://github.com/facebook/react-native/commit/67002e8ae3c924bbba2e742dc1292b45f838a004) and [there](https://github.com/facebook/react-native/commit/3a8b50ad550b176bbce5713c5c74e1318c10f2a0) until **Experimental** in the name is dropped. 

As for wanting to maintain your own fork of NavigationExperimental, not sure if I'd recommend that but I understand your frustration so [here](https://github.com/ericvicenti/rn-sample/tree/master/react-navigation)'s how you'd do it. 

🍺

**Comment by ptomasroos** [comment]
I agree that the talk give some clear insights on the road ahead

**Comment by aksonov** [comment]
Okey, i've made fork and will use it until API will be stabilized, now RNRF doesn't depend from RN API anymore, so users could upgrade to latest RN without problems.
