### ISSUE TITLE
Is Navigation.Header always 64 pixels tall?

### ISSUE THREAD

**Issue by yefim** [ericvicenti/navigation-rfc#83]
I finally found how to start my content under the overlaid header. Now I'm wondering if that number will ever change.

**Comment by chenxsan** [comment]
If we are talking about iOS platform, I think the answer is [yes](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js#L216).

I would suggest using `Navigation.Header.HEIGHT` instead of `64` directly in your code.

**Comment by yefim** [comment]
Perfect, thank you!
