### ISSUE TITLE
Position / Progress role in the transition from one scene to another

### ISSUE THREAD

**Issue by gorjanz** [ericvicenti/navigation-rfc#85]
I am trying to adjust the NavigationExperimental API for a custom use-case.

Can you please clarify what is the intended role of the _position_ animated value, and the _progress_ animated value, in the direction of, why do we need both?

I understand why/how they are used, but why cannot we always express the situation with the _progress_ value, and then interpolate twice for the entering and leaving scene (one interpolation for the entering scene (enter/exit), one for the leaving scene (enter/exit), all mapped with an input od [0,1], same as the progress value).

**Comment by ericvicenti** [comment]
At this point, position is mostly used as a convenience when you prefer to write your scenes that way.

cc @hedgerwang

**Comment by gorjanz** [comment]
Thanks for the fast response.
In my case, I am using the _progress_ value, to do transitions, for the _entering_ / _exiting_ scene, in a way, declaratively, where I give four transitions mapped to the 0->1 progress, two for the entering scene (way of entering / way of exiting) and two for the exiting scene, in the same way, switching them based on if it's a drill-down or back action. 
Where I run into an issue here, is that the _swipe-back_ behaviour is connected with the _position_ value via the pan handlers.

I'll try to define this behaviour also via the progress value, as well, as a next step, and we'll see how that goes...

And also, since this is not really an issue, more of a discussion or a request for an advice, I'll close this thread...

Thanks for your great work on the Navigation Experimental so-far... 👍

**Comment by ericvicenti** [comment]
Ah, I see how that could cause confusion.

Currently progress is only used when the end-state is known.

We can consider removing position if somebody demonstrates that all the use cases can be satisfied without it. But I probably won't be pushing the effort.

**Comment by hedgerwang** [comment]
@gorjanz : 

Say that if you want to replace card A with B. 

before :

```
{index: 0, routes: [{key: 'A']}]
```

after:

```
{index: 0, routes: [{key: 'A']}]
```

For this case, the `position` does not change (and its value will stay at `0`) but the `progress` will change so that you could animate both card A and B.

**Comment by gorjanz** [comment]
I guess it's

```
{index: 0, routes: [{key: 'B']}]
```

in the second moment, but I get your point.

My real question was, if the _progress_ value, serves as a kind of indicator, where we are at with the transition from one scene to another, why is the _position_ value used in the panHandler, for the _back-swipe_ gesture... because IMHO you are also kind of transitioning when you start the _back-swipe_ gesture... If you decide to cancel, and not go back, you can reset the value to 0, or if you swipe enough (from left to right), you can just animate the value up till 1.

Do you see problems with this scenario, something that I am missing?

**Comment by ericvicenti** [comment]
@gorjanz You make a good point but I've realized one example which can demonstrate why position and progress are independent in the current implementation.

Take the pager example, where you can swipe forward and back. Progress is helpful, but only if you know what the destination state is, which the gesture does not. If you only look at progress, there's no easy way to build an animation where you can gesture in both directions.

**Comment by gorjanz** [comment]
You are absolutelly right.

Today I removed the _position_ completely, and I am now facing two issues. One is the direction that you mentioned, and the second is a flicker, when going back, because in order to do the transition, you again need to go from 0 -> 1, and you are already starting from 1.
