### ISSUE TITLE
Stack Reducer & Tabs Reducer

### ISSUE THREAD

**Issue by smkhalsa** [ericvicenti/navigation-rfc#86]
@ericvicenti were the "Stack Reducer" and "Tabs Reducer" dropped when this moved over to the react native repo?

If so, do they still exist somewhere?

**Comment by jmurzy** [comment]
Bundled reducers (i.e. `TabsReducer`, `StackReducer`) are deprecated. See https://github.com/ericvicenti/navigation-rfc/issues/77#issuecomment-223406827

🍺

**Comment by smkhalsa** [comment]
@jmurzy Got it. Thank you.
